### ISSUE TITLE
[Feature request] Autoplay macro (honouring stoppoints)

### ISSUE THREAD

**Issue by bendtherules** [nodename/vscode-hacker-typer#3]
@nodename I saw that you are building this in the other issue, but I wanted to make a official feature request to add autoplay macro feature.

Feature - 
1. I should be able to start playing the macro as autoplay directly or start as normal play and then go into autoplay mode at some point
2. Speed of autoplay should be configurable (or have sensible default)
2. It should (optionally) honor stoppoints and wait there
3. (Maybe) I should be able to stop autoplay at some point (say at stoppoint) and continue rest of it manually.

Because there are so many optional settings within this, it would be good to have some sort of hackertyper setting file - where all these details can be configured.

**Comment by nodename** [comment]
Autoplay is already implemented. The ` (backtick) key toggles autoplay. However it does not offer configurable speed or the ability to ignore stop points.

**Comment by bendtherules** [comment]
Thanks a lot, I'll try it out. Closing it for now.
